# render.yaml - Configuration spécifique pour votre projet
services:
  - type: web
    name: ecommerce-project # Nom exact de votre service Render
    plan: free
    dockerfile: Dockerfile # Chemin relatif depuis la racine
    env: docker
    port: 10000 # Port obligatoire pour les containers Docker sur Render

    # Configuration des variables d'environnement
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: "http://*:10000" # Port interne du container
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: dbecommerce_ugor # Doit correspondre exactement au nom de votre DB dans Render
          property: connectionString

    # Paramètres avancés
    healthCheckPath: /health # Endpoint de vérification
    autoDeploy: true # Déploiement automatique sur push Git

    # Ressources (optionnel)
    resources:
      memory: 512MB
      cpu: 0.25
