# render.yaml
services:
  - type: web
    name: ecommerce-app
    plan: free
    dockerfile: Dockerfile
    env: docker
    port: 10000 # Port obligatoire pour Docker sur Render

    # Variables essentielles
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://*:10000"
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: dbecommerce_ugor
          property: connectionString
